2023-02-24 09:18:39 DEBUG:busco.run_BUSCO	Command line: /home/inf-52-2022/miniconda3/envs/busco/bin/busco -c 100 -i ./fasta_to_analyse -l saccharomycetes_odb10 -o output -m genome
2023-02-24 09:18:39 INFO:busco.run_BUSCO	***** Start a BUSCO v5.4.4 analysis, current time: 02/24/2023 09:18:39 *****
2023-02-24 09:18:39 DEBUG:busco.ConfigManager	Getting config file
2023-02-24 09:18:39 INFO:busco.ConfigManager	Configuring BUSCO with local environment
2023-02-24 09:18:39 INFO:busco.BuscoConfig	Mode is genome
2023-02-24 09:18:39 ERROR:busco.BuscoRunner	A run with the name /home/inf-52-2022/De_novo_assembly/06_Busco/output already exists...
	If you are sure you wish to overwrite existing files, please use the -f (force) option
2023-02-24 09:18:39 DEBUG:busco.BuscoRunner	A run with the name /home/inf-52-2022/De_novo_assembly/06_Busco/output already exists...
	If you are sure you wish to overwrite existing files, please use the -f (force) option
Traceback (most recent call last):
  File "/home/inf-52-2022/miniconda3/envs/busco/lib/python3.9/site-packages/busco/run_BUSCO.py", line 70, in run
    self.load_config()
  File "/home/inf-52-2022/miniconda3/envs/busco/lib/python3.9/site-packages/busco/run_BUSCO.py", line 62, in load_config
    self.config_manager.load_busco_config_main()
  File "/home/inf-52-2022/miniconda3/envs/busco/lib/python3.9/site-packages/busco/BuscoLogger.py", line 62, in wrapped_func
    self.retval = func(*args, **kwargs)
  File "/home/inf-52-2022/miniconda3/envs/busco/lib/python3.9/site-packages/busco/ConfigManager.py", line 58, in load_busco_config_main
    self.config_main.validate()
  File "/home/inf-52-2022/miniconda3/envs/busco/lib/python3.9/site-packages/busco/BuscoConfig.py", line 526, in validate
    self._check_no_previous_run()
  File "/home/inf-52-2022/miniconda3/envs/busco/lib/python3.9/site-packages/busco/BuscoConfig.py", line 737, in _check_no_previous_run
    raise BatchFatalError(
busco.Exceptions.BatchFatalError: A run with the name /home/inf-52-2022/De_novo_assembly/06_Busco/output already exists...
	If you are sure you wish to overwrite existing files, please use the -f (force) option
2023-02-24 09:18:39 ERROR:busco.BuscoRunner	BUSCO analysis failed!
2023-02-24 09:18:39 ERROR:busco.BuscoRunner	Check the logs, read the user guide (https://busco.ezlab.org/busco_userguide.html), and check the BUSCO issue board on https://gitlab.com/ezlab/busco/issues

